services:
    jt_mail.event_listener.pre_sending:
        class: JT\MailBundle\EventListener
        arguments: ["@jt_mail.pre_mailer"]
        tags:
            - { name: jt_mail.pre_sending }

    jt_mail.pre_mailer:
        class: JT\MailBundle\Mailer\PreMailer
        arguments: ["%jt_mail.pre_mailer.options%"]
